// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// slobe_admm_cpp
Rcpp::List slobe_admm_cpp(const Eigen::VectorXd& start, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Xinit, const Eigen::VectorXd& y, double a_prior, double b_prior, const Eigen::MatrixXd& covariance, double sigma, double fdr, double tolerance, bool known_sigma, int max_iterations, bool verbose, bool bh, bool known_covariance);
RcppExport SEXP _slobe_slobe_admm_cpp(SEXP startSEXP, SEXP XSEXP, SEXP XinitSEXP, SEXP ySEXP, SEXP a_priorSEXP, SEXP b_priorSEXP, SEXP covarianceSEXP, SEXP sigmaSEXP, SEXP fdrSEXP, SEXP toleranceSEXP, SEXP known_sigmaSEXP, SEXP max_iterationsSEXP, SEXP verboseSEXP, SEXP bhSEXP, SEXP known_covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Xinit(XinitSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type a_prior(a_priorSEXP);
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type fdr(fdrSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type known_sigma(known_sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type bh(bhSEXP);
    Rcpp::traits::input_parameter< bool >::type known_covariance(known_covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(slobe_admm_cpp(start, X, Xinit, y, a_prior, b_prior, covariance, sigma, fdr, tolerance, known_sigma, max_iterations, verbose, bh, known_covariance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_slobe_slobe_admm_cpp", (DL_FUNC) &_slobe_slobe_admm_cpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_slobe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
