# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slobe_admm_cpp <- function(start, X, Xinit, y, a_prior, b_prior, covariance, sigma, fdr, tolerance, known_sigma, max_iterations, verbose, bh, known_covariance) {
    .Call(`_slobe_slobe_admm_cpp`, start, X, Xinit, y, a_prior, b_prior, covariance, sigma, fdr, tolerance, known_sigma, max_iterations, verbose, bh, known_covariance)
}

